version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: condominio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/condominio
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles

volumes:
  postgres_data: