services:
  - type: web
    name: gestion-inmuebles
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"

  - type: pserv
    name: gestion-inmuebles-db
    env: postgresql
    plan: starter
    databaseName: gestion_inmuebles
    databaseUser: gestion_inmuebles