# Generated by Django 5.2.6 on 2025-09-20 12:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conceptos_Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Conceptos de Gasto',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edificio', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Tasa_Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Tasas de Cambio',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('requiere_alicuota', models.BooleanField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Gasto',
            },
        ),
        migrations.CreateModel(
            name='Gastos_del_Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_recurrente', models.BooleanField()),
                ('tipo_distribucion', models.CharField(choices=[('Todos', 'Todos'), ('Edificios_Especificos', 'Edificios Específicos')], default='Todos', max_length=25)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('id_concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_mes', to='condominio.conceptos_gasto')),
            ],
            options={
                'verbose_name_plural': 'Gastos del Mes',
            },
        ),
        migrations.CreateModel(
            name='Movimientos_Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('mes_aplicacion', models.DateField()),
                ('descripcion_adicional', models.CharField(blank=True, max_length=200)),
                ('id_gasto_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='condominio.gastos_del_mes')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Gastos',
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=5)),
                ('apartamento', models.CharField(max_length=5)),
                ('alicuota', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='condominio.edificio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='condominio.propietario')),
            ],
            options={
                'verbose_name_plural': 'Inmuebles',
                'unique_together': {('edificio', 'piso', 'apartamento')},
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('monto_deuda_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_cargos_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_interes_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='condominio.inmueble')),
            ],
            options={
                'verbose_name_plural': 'Recibos',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_bancaria', models.CharField(max_length=50, unique=True)),
                ('metodo_pago', models.CharField(default='Transferencia', max_length=20)),
                ('estado_verificacion', models.CharField(choices=[('Por Verificar', 'Por Verificar'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='Por Verificar', max_length=15)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('id_recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='condominio.recibos')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Detalles_Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_gasto', models.CharField(max_length=100)),
                ('monto_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recibo', to='condominio.movimientos_gastos')),
                ('id_recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='condominio.recibos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Recibo',
            },
        ),
        migrations.AddField(
            model_name='conceptos_gasto',
            name='id_tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='condominio.tipos_gasto'),
        ),
        migrations.CreateModel(
            name='Gastos_Edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_edificios', to='condominio.edificio')),
                ('id_gasto_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_edificios', to='condominio.gastos_del_mes')),
            ],
            options={
                'verbose_name_plural': 'Gastos por Edificios',
                'unique_together': {('id_gasto_mes', 'id_edificio')},
            },
        ),
        migrations.CreateModel(
            name='Movimientos_Edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_edificios', to='condominio.edificio')),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_edificios', to='condominio.movimientos_gastos')),
            ],
            options={
                'verbose_name_plural': 'Movimientos por Edificios',
                'unique_together': {('id_movimiento', 'id_edificio')},
            },
        ),
    ]
