# Generated by Django 5.2.6 on 2025-09-20 12:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='alicuota',
            field=models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000001')), django.core.validators.MaxValueValidator(Decimal('1.000000'))]),
        ),
    ]
