# Generated by Django 5.2.6 on 2025-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_inmueble_alicuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos_gasto',
            name='requiere_alicuota',
        ),
        migrations.AddField(
            model_name='tipos_gasto',
            name='tipo_calculo',
            field=models.CharField(choices=[('Comun', 'Gasto Común (Por Alícuota)'), ('No_Comun', 'Gasto No Común (Partes Iguales)')], default='Comun', max_length=10),
        ),
    ]
