# Generated by Django 5.2.6 on 2025-10-12 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_remove_tipos_gasto_requiere_alicuota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_generacion', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('hora_generacion', models.TimeField(default='08:00')),
                ('dia_recordatorio', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('hora_recordatorio', models.TimeField(default='10:00')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Configuración de Recibos',
            },
        ),
        migrations.AddField(
            model_name='detalles_recibo',
            name='tipo_gasto',
            field=models.CharField(choices=[('Comun', 'Común'), ('No_Comun', 'No Común')], default='Comun', max_length=10),
        ),
    ]
