# Generated by Django 5.2.6 on 2025-10-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_configuracion_recibos_detalles_recibo_tipo_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_recibo',
            name='id_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recibo', to='condominio.movimientos_gastos'),
        ),
    ]
