# Generated by Django 5.2.6 on 2025-10-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_alter_detalles_recibo_id_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
