# Generated by Django 5.2.6 on 2025-10-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_recibos_numero_recibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos_Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='condominio.propietario')),
            ],
            options={
                'verbose_name_plural': 'Créditos de Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Historial_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_credito_generado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_transaccion', models.CharField(choices=[('Pago_Completo', 'Pago Completo'), ('Pago_Parcial', 'Pago Parcial'), ('Sobrepago', 'Sobrepago'), ('Aplicacion_Credito', 'Aplicación de Crédito')], max_length=20)),
                ('referencia_bancaria', models.CharField(max_length=50)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('id_recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='condominio.recibos')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='condominio.propietario')),
            ],
            options={
                'verbose_name_plural': 'Historial de Pagos',
            },
        ),
    ]
