# Generated by Django 5.2.6 on 2025-10-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_creditos_propietario_historial_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=10),
        ),
    ]
