# Generated by Django 5.2.6 on 2025-10-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0008_recibos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_recibos',
            name='mensaje_nuevo_recibo',
            field=models.TextField(default='Hola {nombre}, tienes un nuevo recibo pendiente por ${monto}. Descarga tu recibo aquí: {link_pdf}'),
        ),
        migrations.AddField(
            model_name='configuracion_recibos',
            name='mensaje_recordatorio',
            field=models.TextField(default='Hola {nombre}, tienes recibos pendientes: {meses_pendientes}. Total adeudado: ${total_deuda}'),
        ),
        migrations.AddField(
            model_name='configuracion_recibos',
            name='whatsapp_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracion_recibos',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='configuracion_recibos',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
